/**
 * Issue 040: Deterministic Web-profile SoundEffect `.xnb` fixture assembler.
 *
 * The bytes produced here are byte-identical to the committed repository fixture
 * `examples/ContentExample/Content/audio/blip.xnb`, which is generated by
 * `scripts/build-audio-content-fixture.mjs` from this same module. The packaged
 * proof rebuilds the fixture in the WebView and pins its SHA-256, so the bytes
 * mounted at proof time are provably the committed fixture bytes.
 *
 * Layout follows the pinned MonoGame 3.8.5.1 `SoundEffectWriter`/`SoundEffectReader`
 * contract:
 *   XNB header : "XNB" | platform 'b' (Web) | version 5 | flags 0 | int32 file size
 *   body       : 7-bit reader count | reader type string | int32 reader version
 *                7-bit shared resource count | 7-bit root reader selector
 *                int32 format size | WAVEFORMATEX bytes
 *                int32 data size   | PCM data
 *                int32 loop start  | int32 loop length | int32 duration (ms)
 *
 * Every sample is produced from an integer lookup table, never from
 * `Math.sin`, so Node and JavaScriptCore emit identical bytes.
 */

export const SOUND_EFFECT_READER_TYPE =
  "Microsoft.Xna.Framework.Content.SoundEffectReader, MonoGame.Framework, Version=3.8.5.1, Culture=neutral, PublicKeyToken=null";

export const WEB_PLATFORM_BYTE = 0x62; // 'b'
export const XNB_FORMAT_VERSION = 5;

/** 441 Hz single-cycle 16-bit signed sine table (50 samples at 22 050 Hz, peak 8192 ≈ -12 dBFS). */
const SINE_CYCLE = [
  0, 1027, 2037, 3016, 3947, 4815, 5608, 6312, 6917, 7412,
  7791, 8047, 8176, 8176, 8047, 7791, 7412, 6917, 6312, 5608,
  4815, 3947, 3016, 2037, 1027, 0, -1027, -2037, -3016, -3947,
  -4815, -5608, -6312, -6917, -7412, -7791, -8047, -8176, -8176, -8047,
  -7791, -7412, -6917, -6312, -5608, -4815, -3947, -3016, -2037, -1027,
] as const;

export const ISSUE040_FIXTURE_SAMPLE_RATE = 22_050;
export const ISSUE040_FIXTURE_CHANNELS = 1;
export const ISSUE040_FIXTURE_BITS_PER_SAMPLE = 16;
export const ISSUE040_FIXTURE_SAMPLE_COUNT = ISSUE040_FIXTURE_SAMPLE_RATE; // exactly 1.000 s
export const ISSUE040_FIXTURE_DURATION_MS = 1_000;
export const ISSUE040_FIXTURE_ASSET_PATH = "audio/blip.xnb";
export const ISSUE040_FIXTURE_ASSET_NAME = "audio/blip";

/** SHA-256 of `buildIssue040SoundFixture()` and of the committed repository fixture. */
export const ISSUE040_FIXTURE_SHA256 =
  "247f196aa6e26aa2982286d20dbd8a91a40beaa90b76e445bf70fda6ba4a70eb";

/** Byte length of `buildIssue040SoundFixture()` and of the committed repository fixture. */
export const ISSUE040_FIXTURE_BYTE_LENGTH = 44_280;

export interface SoundEffectXnbOptions {
  readonly platformByte?: number;
  readonly formatVersion?: number;
  readonly flags?: number;
  readonly readerType?: string;
  readonly readerVersion?: number;
  readonly sharedResourceCount?: number;
  readonly rootReaderSelector?: number;
  readonly formatTag?: number;
  readonly channels?: number;
  readonly sampleRate?: number;
  readonly bitsPerSample?: number;
  readonly blockAlign?: number;
  readonly averageBytesPerSecond?: number;
  readonly cbSize?: number;
  readonly formatSizeOverride?: number;
  readonly data: Uint8Array;
  readonly declaredDataSize?: number;
  readonly loopStart?: number;
  readonly loopLength?: number;
  readonly durationMs?: number;
  readonly trailingBytes?: Uint8Array;
  readonly declaredFileSizeOverride?: number;
}

class ByteWriter {
  private readonly parts: number[] = [];

  u8(value: number): void {
    this.parts.push(value & 0xff);
  }

  bytes(values: ArrayLike<number>): void {
    for (let index = 0; index < values.length; index++) this.parts.push(values[index] & 0xff);
  }

  i16(value: number): void {
    this.u8(value);
    this.u8(value >> 8);
  }

  i32(value: number): void {
    this.u8(value);
    this.u8(value >> 8);
    this.u8(value >> 16);
    this.u8(value >> 24);
  }

  sevenBit(value: number): void {
    let remaining = value >>> 0;
    while (remaining >= 0x80) {
      this.u8((remaining & 0x7f) | 0x80);
      remaining >>>= 7;
    }
    this.u8(remaining);
  }

  utf8String(value: string): void {
    const encoded = new TextEncoder().encode(value);
    this.sevenBit(encoded.length);
    this.bytes(encoded);
  }

  toUint8Array(): Uint8Array {
    return Uint8Array.from(this.parts);
  }
}

/** Builds the deterministic 16-bit signed mono PCM payload for the fixture. */
export function buildIssue040FixturePcm(): Uint8Array {
  const data = new Uint8Array(ISSUE040_FIXTURE_SAMPLE_COUNT * 2);
  const view = new DataView(data.buffer);
  const fadeSamples = 220; // ~10 ms click-free fade in and out
  for (let index = 0; index < ISSUE040_FIXTURE_SAMPLE_COUNT; index++) {
    const rawSample: number = SINE_CYCLE[index % SINE_CYCLE.length];
    const fromStart = index;
    const fromEnd = ISSUE040_FIXTURE_SAMPLE_COUNT - 1 - index;
    const rampIn = fromStart < fadeSamples ? fromStart : fadeSamples;
    const rampOut = fromEnd < fadeSamples ? fromEnd : fadeSamples;
    const ramp = rampIn < rampOut ? rampIn : rampOut;
    // Integer-only envelope keeps the byte stream identical across JS engines.
    const sample = Math.trunc((rawSample * ramp) / fadeSamples);
    view.setInt16(index * 2, sample, true);
  }
  return data;
}

/** Assembles a Web-profile SoundEffect `.xnb` with fully controllable fields. */
export function buildSoundEffectXnb(options: SoundEffectXnbOptions): Uint8Array {
  const channels = options.channels ?? ISSUE040_FIXTURE_CHANNELS;
  const bitsPerSample = options.bitsPerSample ?? ISSUE040_FIXTURE_BITS_PER_SAMPLE;
  const sampleRate = options.sampleRate ?? ISSUE040_FIXTURE_SAMPLE_RATE;
  const blockAlign = options.blockAlign ?? (channels * bitsPerSample) / 8;
  const averageBytesPerSecond = options.averageBytesPerSecond ?? sampleRate * blockAlign;

  const format = new ByteWriter();
  format.i16(options.formatTag ?? 1);
  format.i16(channels);
  format.i32(sampleRate);
  format.i32(averageBytesPerSecond);
  format.i16(blockAlign);
  format.i16(bitsPerSample);
  format.i16(options.cbSize ?? 0);
  const formatBytes = format.toUint8Array();

  const body = new ByteWriter();
  body.sevenBit(1);
  body.utf8String(options.readerType ?? SOUND_EFFECT_READER_TYPE);
  body.i32(options.readerVersion ?? 0);
  body.sevenBit(options.sharedResourceCount ?? 0);
  body.sevenBit(options.rootReaderSelector ?? 1);
  body.i32(options.formatSizeOverride ?? formatBytes.length);
  body.bytes(formatBytes);
  body.i32(options.declaredDataSize ?? options.data.length);
  body.bytes(options.data);
  body.i32(options.loopStart ?? 0);
  body.i32(options.loopLength ?? 0);
  body.i32(options.durationMs ?? ISSUE040_FIXTURE_DURATION_MS);
  if (options.trailingBytes) body.bytes(options.trailingBytes);
  const bodyBytes = body.toUint8Array();

  const header = new ByteWriter();
  header.bytes([0x58, 0x4e, 0x42]); // "XNB"
  header.u8(options.platformByte ?? WEB_PLATFORM_BYTE);
  header.u8(options.formatVersion ?? XNB_FORMAT_VERSION);
  header.u8(options.flags ?? 0);
  header.i32(options.declaredFileSizeOverride ?? 10 + bodyBytes.length);
  const headerBytes = header.toUint8Array();

  const result = new Uint8Array(headerBytes.length + bodyBytes.length);
  result.set(headerBytes, 0);
  result.set(bodyBytes, headerBytes.length);
  return result;
}

/** Builds the exact committed issue 040 fixture bytes. */
export function buildIssue040SoundFixture(): Uint8Array {
  const data = buildIssue040FixturePcm();
  return buildSoundEffectXnb({
    data,
    loopStart: 0,
    loopLength: ISSUE040_FIXTURE_SAMPLE_COUNT,
    durationMs: ISSUE040_FIXTURE_DURATION_MS,
  });
}
